task:
  name: gcc-build-release
  container:
    image: debian:buster
  env:
    CC: gcc
    CXX: g++
  build_script:
    - apt-get update
    - apt-get install --assume-yes meson ninja-build
    - ${CXX} --version
    - ./scripts/build.sh release
