task:
  name: clang-build-release
  container:
    image: mhhollomon/yalr-ci:debian
    memory: 8G
  env:
    CC: clang
    CXX: clang++
  build_script:
    - ${CXX} --version
    - ./scripts/build.sh release
