task:
  name: gcc-build-release
  container:
    image: gcc:8
  env:
    CC: gcc
    CXX: g++
  build_script:
    - apt-get update
    - apt-get install --assume-yes meson ninja
    - ${CXX} --version
    - ./scripts/build.sh release
