task:
  name: gcc-build-release
  container:
    image: mhhollomon/yalr-ci:alpine
    memory: 2G
  env:
    CC: gcc
    CXX: g++
  build_script:
    - ${CXX} --version
    - ./scripts/build.sh release
